version: '3.8'

services:
    app:
        build:
            args:
                uid: 1000
            context: .
            dockerfile: docker/Dockerfile
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - product-crud-network

    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3308:3306"
        volumes:
            - db_data:/var/lib/mysql
            - ./docker/nginx_logs:/var/log/nginx/
        networks:
            - product-crud-network


    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - product-crud-network

volumes:
    db_data:

networks:
    product-crud-network:
        driver: bridge
